const collection = [
  {
    email: 'melany.wijngaard@example.com',
    gender: 'female',
    phone_number: '(727)-033-9347',
    birthdate: 608022796,
    location: {
      street: '2431 predikherenkerkhof',
      city: 'staphorst',
      state: 'gelderland',
      postcode: 64265,
    },
    username: 'bigpeacock217',
    password: 'eagle',
    first_name: 'melany',
    last_name: 'wijngaard',
    title: 'miss',
    picture: 'women/70.jpg',
  },
  {
    email: 'nanna.pedersen@example.com',
    gender: 'female',
    phone_number: '43672992',
    birthdate: 591428535,
    location: {
      street: '2177 fåborgvej',
      city: 'aarhus',
      state: 'syddanmark',
      postcode: 87547,
    },
    username: 'purpleduck599',
    password: 'davids',
    first_name: 'nanna',
    last_name: 'pedersen',
    title: 'ms',
    picture: 'women/68.jpg',
  },
  {
    email: 'amelia.mercier@example.com',
    gender: 'female',
    phone_number: '(168)-747-5950',
    birthdate: 1132298571,
    location: {
      street: '7454 rue duquesne',
      city: 'echandens-denges',
      state: 'vaud',
      postcode: 3811,
    },
    username: 'whitefrog218',
    password: 'forest',
    first_name: 'amelia',
    last_name: 'mercier',
    title: 'madame',
    picture: 'women/91.jpg',
  },
  {
    email: 'sarah.oliver@example.com',
    gender: 'female',
    phone_number: '0761-814-654',
    birthdate: 1038915780,
    location: {
      street: '3503 manor road',
      city: 'manchester',
      state: 'highlands and islands',
      postcode: 'I30 5ZF',
    },
    username: 'purplebear893',
    password: 'boat',
    first_name: 'sarah',
    last_name: 'oliver',
    title: 'ms',
    picture: 'women/73.jpg',
  },
  {
    email: 'عسل.مرادی@example.com',
    gender: 'female',
    phone_number: '0925-326-2063',
    birthdate: 417058382,
    location: {
      street: '4981 شهید بهشتی',
      city: 'پاکدشت',
      state: 'مرکزی',
      postcode: 68555,
    },
    username: 'ticklishfish813',
    password: 'zaq12wsx',
    first_name: 'عسل',
    last_name: 'مرادی',
    title: 'mrs',
    picture: 'women/65.jpg',
  },
];

const flatten = collection.flatMap(item => [item, item.location]);

console.log({ flatten });
